### ISSUE TITLE
New comment model completely destroys comments.

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#505]
Jesus Christ. The monkeys have fucking done it again. They completely fucked comments. Now, instead of the `commentThreadRenderer` containing the comment data, like a SANE FUCKING API, they decided it would be a great idea to instead give it a key (`commentKey`) that refers to an object in a completely separate array (`frameworkUpdates.entityBatchUpdate.mutations`) which also have this key (`entityKey`) and have the actual comment content. I seriously did not think they could get any more retarded, but they've done it.

Anyways, here's a full `next` continuation response containing this FUCKTARDED change:

[garbage.json](https://github.com/Rehike/Rehike/files/14105708/garbage.json)

**Comment by ephemeralViolette** [comment]
https://github.com/Rehike/Rehike/commit/de6ac9d3187260027d4e30a0061f6c3651882339

I wrote a few classes to make parsing these pieces of shit easier, but it's still tedious and I don't want to work on it.

**Comment by YukisCoffee** [comment]
I think this is mostly fixed now, but I'll keep the issue open in case there's anything else that's important.

**Comment by bluedragon-cairo** [comment]
Now the like/dislike button on comments doesn't work, heart button is broken(all comments in my channel has hearts and my comment on other channel has a heart button), replying throws visual errors(though reloading shows my new reply) since about two weeks ago

**Comment by Xammand** [comment]
I can't add a comment or add a reply on any video, I also have the same issues as bluedragon.

**Comment by bluedragon-cairo** [comment]
Posting the comment shows infinite loading but reloading page shows your new comment as far as I know... I temporarily switched to Vorapis V3 until Rehike fixes comments again so now sure about now though

**Comment by syndiate** [comment]
@bluedragon-cairo @Xammand Posting comments and liking/disliking comments work now, but posting replies still don't

**Comment by Xammand** [comment]
@syndiate Yup that stuff works and replies don't for me. I'm also still having issues where every comment on a video I post have the heart on them even though I never favorited them. Clicking on it doesn't do anything.

**Comment by kawapure** [comment]
Comments have been back to regular functionality for a while now. This issue will be closed. Any new issues pertaining to comment viewmodel parsing should be opened separately.
